#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

# FILE for interface definitions
CONF=/etc/network/interfaces

# Try to load from /misc instead of /etc
if [ -f /misc/network/interfaces ]; then
	CONF=/misc/network/interfaces
fi

case "$1" in
  start)
	printf "Starting network: "
	/sbin/ifup -a -i $CONF
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a -i $CONF
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

