#!/bin/sh

DEV=
YES=

check_device_size()
{
	CAP=$(blockdev --getsize64 $1)
	if [ -z ${CAP} ]; then
		echo "The target device $1 not valid."
		echo 2;
	fi

	if [ ${CAP} -lt $2 ]; then
		echo "The Target device $1(${CAP} < $2) too small."
		exit 3;
	fi
}

for var in "$@"; do
	if [[ "${var}" = "-y" ]]; then
		YES=y
	else
		DEV=${var}
	fi
done

if [[ -z "${DEV}" ]]; then
	echo "Usage: install-sys <block device>"
	echo "  Example: install-sys /dev/sda"
	exit 1;
fi

check_device_size ${DEV}1 100000000
check_device_size ${DEV}2 200000000
check_device_size ${DEV}3 200000000
check_device_size ${DEV}4 200000000
check_device_size ${DEV}5 200000000
check_device_size ${DEV}6 200000000

echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "!!! Warning: All data on \"${DEV}\" will be destroy !!!"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo
if [[ -z "${YES}" ]]; then
	read -p "Are you sure? [yes|no]: "

	case ${REPLY} in
		y|yes|Y|YES) ;;
		*) exit 0;;
	esac
fi

mount ${DEV}1 /mnt
rm -rf /mnt/*.*
tar -xvf boot.tgz -C/mnt/

echo
echo "======================================================="
echo "===        System installation complete.            ==="
echo "======================================================="
exit $?

