#!/bin/sh
#
# Start monit
#

DAEMON=/usr/bin/monit
NAME=monit
PIDFILE=/var/run/monit.pid

case "$1" in
	start)
		echo "Starting ${NAME} ..."
		start-stop-daemon -S -n ${NAME} -p ${PIDFILE} -x ${DAEMON}
		;;
	stop)
		echo "Stopping ${NAME} ..."
		start-stop-daemon -K -n ${NAME} -p ${PIDFILE}
		;;
	restart|reload)
		echo "Restarting ${NAME} ..."
		start-stop-daemon -K -n ${NAME} -p ${PIDFILE}
		start-stop-daemon -S -n ${NAME} -p ${PIDFILE} -x ${DAEMON}
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
