#!/bin/sh
#
# Start cvr-mil-qt
#

DAEMON=/usr/bin/cvr-mil-qt
NAME=cvr-mil-qt
PIDFILE=/var/run/cvr-mil-qt.pid
OPTS=

case "$1" in
	start)
		echo "Starting ${NAME} ..."                
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	stop)
		echo "Stopping ${NAME} ..."
		start-stop-daemon -K -p ${PIDFILE}
		;;
	restart|reload)
		echo "Restarting ${NAME} ..."
		start-stop-daemon -K -p ${PIDFILE}
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?

