#!/bin/sh
#
# Start ethernet over USB ...
#

GADGET_DIR=/sys/kernel/config/usb_gadget/g1

case "$1" in
	start)
		echo "Starting usbeth ..."
		modprobe libcomposite
		modprobe u_ether
		modprobe usb_f_rndis

		mount -t configfs none /sys/kernel/config

		mkdir ${GADGET_DIR}
		cd ${GADGET_DIR}

		echo "64" > bMaxPacketSize0
		echo "0x200" > bcdUSB
		echo "0x100" > bcdDevice
		echo "0x03FD" > idVendor
		echo "0x0500" > idProduct

		mkdir functions/rndis.usb0
		mkdir configs/c1.1

		ln -s functions/rndis.usb0 configs/c1.1/

		echo "ci_hdrc.0" > UDC
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

