#!/bin/sh
#
# Start ftpd
#

DAEMON=/usr/bin/tcpsvd
NAME=ftpd
PIDFILE=/var/run/ftpd.pid
OPTS="0.0.0.0 21 ftpd -w /"

case "$1" in
	start)
		echo "Starting ${NAME} ..."
		# Start the daemon
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	stop)
		echo "Stopping ${NAME} ..."
		# Kill the daemon with pidfile
		start-stop-daemon -K -p ${PIDFILE}
		;;
	restart|reload)
		echo "Restarting ${NAME} ..."
		start-stop-daemon -K -p ${PIDFILE}
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
