#!/bin/sh
# 
# Start config the adv7391 chip
#

case $1 in
	start)
		echo "Start adv7391 configure ..."
		i2cload -f -y 1 /etc/mpcam/adv7391.conf
		;;
	stop)
		;;
	reload|restart)
		i2cload -f -y 1 /etc/mpcam/adv7391.conf
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?

