################################################################################
#
# arm-trusted-firmware-hisi
#
################################################################################

ARM_TRUSTED_FIRMWARE_HISI_VERSION = 2.0.3.1-Hi3559AV100
ARM_TRUSTED_FIRMWARE_HISI_SOURCE = arm-trusted-firmware-$(ARM_TRUSTED_FIRMWARE_HISI_VERSION).tar.gz
ARM_TRUSTED_FIRMWARE_HISI_SITE = https://cgit.vaxpl.com/rdst/arm-trusted-firmware/snapshot
ARM_TRUSTED_FIRMWARE_HISI_LICENSE = GPL-2.0
ARM_TRUSTED_FIRMWARE_HISI_LICENSE_FILES = COPYING

ARM_TRUSTED_FIRMWARE_HISI_DEPENDENCIES = linux
ARM_TRUSTED_FIRMWARE_HISI_INSTALL_IMAGES = YES

ARM_TRUSTED_FIRMWARE_HISI_CHIP = $(call qstrip,$(BR2_TARGET_ARM_TRUSTED_FIRMWARE_HISI_CHIP))
ARM_TRUSTED_FIRMWARE_HISI_CPU_TYPE = $(call qstrip,$(BR2_TARGET_ARM_TRUSTED_FIRMWARE_HISI_CPU_TYPE))
ARM_TRUSTED_FIRMWARE_HISI_ENVS = \
	BL33=$(BINARIES_DIR)/uImage \
	BL33_SEC=0 \
	BUILD_STRING=$(ARM_TRUSTED_FIRMWARE_HISI_CPU_TYPE) \
	CCI_UP=0 \
	CROSS_COMPILE=$(TARGET_CROSS) \
	DEBUG=1 \
	HISILICON=1 \
	PLAT=$(ARM_TRUSTED_FIRMWARE_HISI_CHIP) \
	SPD=none

define ARM_TRUSTED_FIRMWARE_HISI_BUILD_CMDS
	$(MAKE) -C $(@D) $(ARM_TRUSTED_FIRMWARE_HISI_ENVS) fip
endef

define ARM_TRUSTED_FIRMWARE_HISI_INSTALL_IMAGES_CMDS
	$(INSTALL) -m 0644 $(@D)/build/$(ARM_TRUSTED_FIRMWARE_HISI_CHIP)/debug/fip.bin \
		$(BINARIES_DIR)/uImage-$(ARM_TRUSTED_FIRMWARE_HISI_CHIP)-$(ARM_TRUSTED_FIRMWARE_HISI_CPU_TYPE)
endef

$(eval $(generic-package))
