#!/bin/sh
#
# Start mxcfb ...
#

case "$1" in
	start)
		echo "Starting mxcfb ..."
		/usr/bin/mxcfb -d /dev/fb0 -g 0
		/usr/bin/mxcfb -d /dev/fb1 -g 0 -a 255 -k 1 -c 0x00 -l 1 -i 1
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

