#!/bin/sh
#
# Start logging
#

start() {
	echo "Fixing readonly files ..."
	cp -apr /etc/ /var/run/
	mount --bind /var/run/etc /etc
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
