#!/bin/sh

init() {
	echo "Initialize Hi3520D BSP ..."

	./load3520D -i 4720p
}

case $1 in
	start)
		cd /ko && init
		;;
	stop)
		;;
	reload|restart)
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?
