#!/bin/sh
config() {
	echo "Configure QT environment..."	
	export QWS_DISPLAY="LinuxFb:/dev/fb4"
	export QWS_DEPTH=32
	export QT_PLUGIN_PATH="/usr/lib/qt/plugins"
    export QT_QWS_FONTDIR="/usr/lib/fonts"
	#export QWS_MOUSE_PROTO=IntelliMouse:/dev/input/mice
	vrs -qws
}

case $1 in
	start)
		config
		;;
	stop)
		;;
	reload|restart)
		 config
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?
