#!/bin/sh

pr "Staging [1] ..."

# Start all init scripts in /etc/initramfs.d/stage1.d
# executing them in numerical order.
#
for i in /etc/initramfs.d/stage1.d/S??*; do
	pr "Found $(basename $i)"

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			# Source shell script for speed.
			source $i
			;;
		*)
			# No sh extension, so fork subprocess.
			$i
			;;
	esac
done
