#!/bin/sh
#
# Start radar
#

DAEMON=/usr/bin/radar
NAME=radar
PIDFILE=/var/run/radar.pid
OPTS=-qws

case "$1" in
	start)
		echo "Starting ${NAME} ..."                
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	stop)
		echo "Stopping ${NAME} ..."
		start-stop-daemon -K -p ${PIDFILE}
		;;
	restart|reload)
		echo "Restarting ${NAME} ..."
		start-stop-daemon -K -p ${PIDFILE}
		start-stop-daemon -S -b -m -n ${NAME} -p ${PIDFILE} -x ${DAEMON} -- ${OPTS}
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
