#!/bin/sh
block()
{
  iptables --flush
  iptables -A INPUT -p tcp --dport 554 -j REJECT
}
case $1 in
	start)
        block
		;;
	stop)
		;;
	reload|restart)
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?

