#!/bin/sh
reject()
{
  iptables --flush
#  iptables -A INPUT -p tcp --dport 554 -j REJECT
  iptables -A INPUT -j REJECT
}
case $1 in
	start)
        reject
		;;
	stop)
		;;
	reload|restart)
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?

