#!/bin/sh
flush()
{
  netstat -ntl 2> /dev/null | grep -q ':554.*LISTEN'
  while [$? -ne 0]
      do
          netstat -ntl 2> /dev/null | grep -q ':554.*LISTEN'
      done
  iptables --flush
}
case $1 in
	start)
        flush
		;;
	stop)
		;;
	reload|restart)
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?

