#!/bin/sh
flush()
{
  netstat -ntl 2> /dev/null | grep -q ':554.*LISTEN'
  while [ $? -ne 0 ];then
      do
          netstat -ntl 2> /dev/null | grep -q ':554.*LISTEN'
      done
#  sleep 2
  ifconfig eth0 up 
  iptables --flush
}
case $1 in
	start)
        flush
		;;
	stop)
		;;
	reload|restart)
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?

