#!/bin/sh

pr "Staging [2] ..."

P1=/etc/initramfs.d/stage2.d/
P2=/misc/initramfs.d/stage2.d/

# Override scripts in P1 from P2
#
test -d ${P2} && cp -ap ${P2}S* ${P1}

# Start all init scripts in /etc/initramfs.d/stage2.d
# executing them in numerical order.
#
for i in ${P1}S??*; do
	pr "Found $i"

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				. $i
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			$i
			;;
	esac
done
