#!/bin/sh

ADV7182_ADDR=0x21
ADV7340_ADDR=0x6b

I2CG="i2cget -f -y 0"
I2CL="i2cload -f -y -8 0"
I2CS="i2cset -f -y 0"

config() {
	echo "Configure ADV7182 and ADV7340 ..."

	# Test ADV7182
	${I2CG} ${ADV7182_ADDR} 0x00 > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		# Reset the chip
		${I2CS} ${ADV7182_ADDR} 0x0F 0x80 > /dev/null 2>&1
		usleep 200000;
		${I2CL} /etc/hivcap/adv7182.conf
	fi

	# Test ADV7340
	${I2CG} ${ADV7340_ADDR} 0x00 > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		${I2CL} /etc/hivcap/adv7340.conf
	fi
}

case $1 in
	start)
		config
		;;
	stop)
		;;
	reload|restart)
		 config
		;;
	*)
		echo "Usage: $0 [start|stop|reload|restart]"
		exit 1
		;;
esac

exit $?
