#!/bin/sh
#
# Make Basic Nodes
#

make_nodes() {
	mknod /dev/console c 5 1
	mknod /dev/ttyAMA0 c 204 64
	mknod /dev/ttyAMA1 c 204 65
	mknod /dev/ttyS000 c 204 64
	mknod /dev/null    c 1 3
}

case "$1" in
	start)
		make_nodes
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

